spring:
  application:
    name: ProcessApp

  profiles:
    # Укажите один из активных профилей
    active: in-memory
    #active: postgres

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO